kind: pipeline
name: default

workspace:
  path: /source

volumes:
  - name: pnpm-cache
    host:
      path: /root/.pnpm-cache

trigger:
  ref:
    - refs/heads/**

steps:
  - name: install
    image: paperplanecc/baseline-node20:2025.11.30
    volumes:
      - name: pnpm-cache
        path: /source/.pnpm-store
    commands:
      - pnpm i
    environment:
      HUSKY: 0

  - name: check
    image: paperplanecc/baseline-node20:2025.11.30
    commands:
      - pnpm run format
      - pnpm run lint
      - pnpm run check-types

  - name: test
    image: paperplanecc/baseline-node20:2025.11.30
    commands:
      - pnpm run test

  - name: auth
    image: robertstettner/drone-npm-auth
    settings:
      token:
        from_secret: NPM_TOKEN
    when:
      branch:
        - main

  - name: publish
    image: paperplanecc/baseline-node20:2025.11.30
    commands:
      - pnpm run publish
    when:
      branch:
        - main
